name: Secrets Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly scan on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: Detect secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Run TruffleHog OSS
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

    - name: Scan with GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

    - name: Run Semgrep Security Scan
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
        generateSarif: "1"
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    - name: Upload Semgrep results to GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
      if: always()

  dependency-check:
    runs-on: ubuntu-latest
    name: OWASP Dependency Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      env:
        NVDAPI_KEY: ${{ secrets.NVDAPI_KEY }}
        OSS_INDEX_USER: ${{ secrets.OSS_INDEX_USER }}
        OSS_INDEX_TOKEN: ${{ secrets.OSS_INDEX_TOKEN }}
      with:
        project: 'budget-app'
        path: '.'
        format: 'ALL'
        args: >
          --enableExperimental
          --suppression suppressions.xml
          --ossindexApiToken ${{ secrets.OSS_INDEX_TOKEN }}
          --exclude "**/node_modules/**"
          --exclude "**/dist/**"
          --exclude "**/build/**"
          --exclude "**/coverage/**"
          --exclude "**/*.min.js"
          --exclude "**/*.bundle.js"

    - name: Upload Test results
      uses: actions/upload-artifact@v4
      with:
        name: Dependency Check Report
        path: ${{github.workspace}}/reports
      if: always()